import Head from 'next/head'
import{BsFillMoonStarsFill} from 'react-icons/bs';

import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    
    <div>
      
      <Head>
        <title>Sahil Chowkekar Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <main className=' bg-white px-10 '>
        <section className="min-h-screen">
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons'>developedbySahil</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill  className='cursor-pointer text-xl'/> 
            </li>
            <li>
              <a className='bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a>
            
            </li>
          </ul>
        </nav>
        <div>
          <h2>Sahil Chowkekar</h2>
          <h3>Software Engineer</h3>
          <p>
          Hello! My name is Sahil Chowkekar, and I'm currently attending the University of California, Riverside to pursue a master's degree in computer science. I'm a driven learner that is constantly eager to experiment with new technologies and work in various fields. I enjoy learning about new technology. My interests are in computer vision, natural language processing, deep learning, and machine learning.
          </p>
        </div>
        </section>
          
        </main>
       
    </div>
  );
}

